### ISSUE TITLE
Specify resources to import

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#1]
Use case:
Allow people to define urls of custom UI to load. This will keep imports closely related to views and will allow users to very easily share UI.

Schema changes:
Add a new optional `import` key to `ViewType`. Each entry will be an object containing the following info:

 - `url`: Required. Points at the resource to be imported
 - `type`: Required. Values: `html`, `module`, `js`. Specify the type of import.

```yaml
views:
  - import:
      - url: https://example.com/example_custom_ui.html
        type: html
      - url: /local/custom_ui_bla.js
        type: module
      - url: /local/custom_ui_another.js
        type: js
```

Runtime changes:
When setting up the view, if an import key is present, load the selected resources.
