### ISSUE TITLE
Picture-glance not working with entity-filter

### ISSUE THREAD

**Issue by jackjohnsonuk** [home-assistant/ui-schema#101]
picture-glance isn't working alongside entity-filter, it works fine when changed to just glance.

Code used in Demo environment to test:
```
      - type: entity-filter
        entities:
          - light.bed_light
          - light.ceiling_lights
          - light.kitchen_lights
        state_filter:
          - 'off'
        card:
          type: picture-glance
          image: https://images2.roomstogo.com/is/image/roomstogo/br_rm_belmar_black_pan~Belmar-Black-5-Pc-Queen-Bedroom.jpeg?$pdp_gallery_945$
```
Running on Docker Dev environment as of 14/07/2018 9am GMT, but also confirmed to not be working on 0.73.1
