### ISSUE TITLE
Feature request - nestable state_image

### ISSUE THREAD

**Issue by DubhAd** [home-assistant/ui-schema#102]
There are a number of times it would be useful to nest the state images, to allow different images for (say) day and night, and lights on or off, without having to resort to input_selects and automations.

Like you can nest the horizontal and vertical stacks, something like:

```yaml
  state_image:
    "below_horizon": 
      state_image:
        "on": /local/living_room_night_on.png
        "off": /local/living_room_night_off.png
      entity: group.living.room
    "above_horizon": /local/living_room_day.png
  entity_id: sun.sun
```

**Comment by ciotlosm** [comment]
Maybe avoid nesting as it makes it a bit unreadable

```yaml
state_image:
  - image: /local/living_room_day.png
    match:
      sun.sun: above_horizon
  - image: /local/living_room_night_on.png
    match:
      sun.sun: below_horizon
      group.living.room: on
  - image: /local/living_room_night_off.png
    match:
      sun.sun: below_horizon
      group.living.room: off
```
