### ISSUE TITLE
Camera cards should show streaming images

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#11]
I added the following to my config:
```
  - tab_icon: mdi:cctv
    name: Cameras
    cards:
      - type: entities
        entities:
          - camera.porch
```
I see the card, but it doesn't display the streaming images (yet?).

![image](https://user-images.githubusercontent.com/18319734/41612476-13d3c23c-73c1-11e8-820d-c5be14ef11e4.png)

**Comment by balloob** [comment]
If you want to show the camera card as the frontend does, you will need to use the `camera-preview` card.

**Comment by arsaboo** [comment]
```
    cards:
      - type: camera-preview
        entities:
          - camera.porch
```
does not work. I get 

![image](https://user-images.githubusercontent.com/18319734/41621969-30668702-73dc-11e8-84ab-370f14c1ac0f.png)
