### ISSUE TITLE
Show last changed instead of state in glance cards

### ISSUE THREAD

**Issue by RJ** [home-assistant/ui-schema#110]
I would like to override the `state` value displayed on glance cards.

Instead of `detected`/`clear`, the default for `class: motion` sensors, I would like to use a template to instead show the number of minutes since the last motion was detected. So instead of "clear", it would say "5 mins ago" if motion was detected 5 mins ago.

<img width="508" alt="screenshot 2018-07-18 15 33 16" src="https://user-images.githubusercontent.com/29747/42888417-26913cf6-8aa0-11e8-992a-c61faabebb3c.png">

I would like something like this:

```yaml
cards:
  - type: glance
    title: Motion Sensors
    entities:
      - entity: binary_sensor.kitchen_motion
        name: Top Floor
        # Instead of just clear/detected, show last activation time:
        value_template: {{ states.binary_sensor.kitchen_motion.last_changed | timeago }}
```
