### ISSUE TITLE
Thermostats Listed In Entities Card Missing Current Temperature And Set Point

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/ui-schema#116]
Prior to 0.74 we were able to see the current temperature and the set point.  Now the temperature is missing completely.

YAML

```
  - type: entities
    title: Thermostat
    entities:
    - climate.thermostat_cooling_1
    - climate.thermostat_heating_1
```

actual:
![thermostat_temp_missing](https://user-images.githubusercontent.com/1634145/43021557-e7399830-8c18-11e8-91ea-6c8bd46383b3.png)

expected:
![thermostat_temp_expected](https://user-images.githubusercontent.com/1634145/43021582-0497db94-8c19-11e8-837e-07a9dc6014ce.png)
