### ISSUE TITLE
Vacuum In Entities Card Are Missing The Toggle And Only Showing State As Text

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/ui-schema#117]
Prior to 0.74 the vacuum entities each had their own toggle in the entities card.  Now the toggle is missing and the state of the device is listed.

YAML

```
  - type: entities
    title: Vacuums
    show_header_toggle: false
    entities:
    - vacuum.mr_neato
    - vacuum.mrs_neato
```

actual:
![vacuum_toggle_missing](https://user-images.githubusercontent.com/1634145/43021691-76c43e24-8c19-11e8-80c2-7ddf0d65870b.png)

expected:
![vacuum_toggle_expected](https://user-images.githubusercontent.com/1634145/43021695-7ad9d83e-8c19-11e8-9e98-f63783607038.png)
