### ISSUE TITLE
0.74.0 Errors in log (input_number)

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/ui-schema#118]
Everytime i open a view i see errors like:
```
2018-07-20 23:29:28 ERROR (MainThread) [frontend.js.latest.201807200] http://192.168.123.123:8123/frontend_latest/c5a5df3ec278008029fa.chunk.js:206:702 TypeError: this.shadowRoot.querySelector(...) is null
```
Maybe they are relateted to input components?
Some views without input components show no errors.
If there are more inputs, more errors are raised.

I'm on firefox 61.0.1 with shadowroot and custom elements enabled.

EDIT: No errors in chrome, but i love my FF. :-(

**Comment by c727** [comment]
which inputs?

**Comment by VDRainer** [comment]
If i comment out input_number, the errors are gone.
```
      - type: entities
        title: Switches
        show_header_toggle: false
        entities:
          - switch.mcp23017_test_01
          - switch.mcp23017_test_02
          - switch.mcp23017_test_03
          - switch.mcp23017_test_04
          - switch.mcp23017_test_05
          - switch.tpad_screen
          - switch.sg90_servo
#          - input_number.sg90_servo
```
Every input_number in a view shows two lines of the error in the log.
