### ISSUE TITLE
Theme option should only work for the specified tab

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#12]
I defined two tabs like:
```yaml
title: ARS Home
views:
  - name: Home
    theme: teal
    cards:
      - type: entities
        title: Example
        entities:
          - input_boolean.abodeupdate
          - input_boolean.partymode
          - input_boolean.tvtime
          - media_player.livingroomsonos
  - tab_icon: mdi:home-assistant
    name: Second view
    cards:
      - type: entities
        title: Lots of Kitchen AC
        entities:
          - input_boolean.abodeupdate
          - input_boolean.partymode
          - input_boolean.tvtime
```
Given that I did not define `theme` in the second tab, I was expecting it to have the default theme. But that was not the case. Here are the two tabs:

![image](https://user-images.githubusercontent.com/18319734/41617270-0d8bd59c-73ce-11e8-87ad-adf8d85737f5.png)

![image](https://user-images.githubusercontent.com/18319734/41617295-1a901190-73ce-11e8-8d12-00999e0abc73.png)
