### ISSUE TITLE
0.74.0 Entities Card formatting Text

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/ui-schema#120]
![auswahl_134](https://user-images.githubusercontent.com/26381449/43027368-2a7d6296-8c7a-11e8-96cf-210762f928d1.png)
```
      - type: entities
        title: Vorhersage
        entities:
          - sensor.pws_weather_1d_metric
          - sensor.pws_weather_1n_metric
          - sensor.pws_weather_2d_metric
          - sensor.pws_weather_2n_metric
          - sensor.pws_weather_3d_metric
          - sensor.pws_weather_3n_metric
          - sensor.pws_weather_4d_metric
          - sensor.pws_weather_4n_metric
```
In FF and in Chrome

Last for tonight :-)
