### ISSUE TITLE
Elements don't align perfectly on iOS on the picture-elements card

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#121]
There is a slight discrepancy between how the elements appear on the desktop and on iOS (app as well as Safari). 
![image](https://user-images.githubusercontent.com/18319734/43027787-2b553520-8c4a-11e8-958b-7877a9b5e89a.png)

![image](https://user-images.githubusercontent.com/18319734/43027792-310474b8-8c4a-11e8-84a3-3c76bceb01b5.png)
All these elements appear perfectly on the desktop. Also, not all elements are affected. My config is available [here](https://github.com/arsaboo/homeassistant-config/blob/master/ui-lovelace.yaml).

**Comment by c727** [comment]
provide a test config so someone can check it, nobody will search through your whole config

**Comment by balloob** [comment]
Contribute your floorplan config to our gallery

**Comment by arsaboo** [comment]
Here's a test config that I created to document the issue:
```yaml
title: Home Assistant
views:
  - icon: mdi:home-assistant
    id: home
    title: Home
    cards:
      - type: picture-elements
        # title: Main Level
        image: https://www.roomsketcher.com/wp-content/uploads/2016/10/1-Bedroom-Floor-Plan-600x450.jpg
        elements:
          - type: icon
            icon: mdi:cctv
            entity: camera.porch
            style:
              top: 92.5%
              left: 16%
              transform: rotate(235deg)
              --iron-icon-height: 30px
              --iron-icon-width: 30px
              --iron-icon-stroke-color: black
              --iron-icon-fill-color: rgba(50, 50, 50, .75)
          - type: icon
            icon: mdi:cctv
            entity: camera.patio
            style:
              top: 4.5%
              left: 16%
              transform: rotate(-60deg) scaleX(-1)
              --iron-icon-height: 30px
              --iron-icon-width: 30px
              --iron-icon-stroke-color: black
              --iron-icon-fill-color: rgba(50, 50, 50, .75)
          - type: icon
            icon: mdi:cctv
            entity: camera.backyard
            style:
              top: 5%
              left: 78%
              transform: rotate(60deg)
              --iron-icon-height: 30px
              --iron-icon-width: 30px
              --iron-icon-stroke-color: black
              --iron-icon-fill-color: rgba(50, 50, 50, .75)
```
Here's what I see on the desktop:
![image](https://user-images.githubusercontent.com/18319734/43036754-2db85f5a-8cd5-11e8-98ea-8419d2949351.png)

On mobile:
![image](https://user-images.githubusercontent.com/18319734/43036760-3c4b55ae-8cd5-11e8-96a5-7724241c2bcb.png)

@balloob If you like this test config, I can add it as a demo card with more elements.
