### ISSUE TITLE
Set column width for a card

### ISSUE THREAD

**Issue by Grayda** [home-assistant/ui-schema#123]
Would it be feasible to have an option to set a column width for one or more cards?

For example I might want a single card to stretch half way or even all the way across the page. Horizontal Stack doesn't quite cut it because that squeezes multiple cards into a single column, not multiple cards into a defined number of columns

Maybe something like this:

```yaml
- type: columns
  width: 6 # Assuming a 12 column page
  cards:
    - type: glance
      ...
```

**Comment by andrey-git** [comment]
How would that work if the card is not at the top of the page?

**Comment by Grayda** [comment]
I made a quick mockup using MaterializeCSS, which I guess HA doesn't use, but gives a good demo of how it would work: https://codepen.io/anon/pen/GBWRLp

As you can see, Row 2 has DIVs that add up to more than 12 columns. The Row 2, 6 Column card simply moves on to the next line. Removing the row markup makes it fit a little better: https://codepen.io/anon/pen/JBWjqx

I admit that they don't fall into a perfect grid (in the first example you'd expect a card from Row 3 to move up to fill out the rest of Row 2) but I'm sure users of this feature would be careful about not leaving gaps and stuff.

**Comment by Grayda** [comment]
If set up correctly, there wouldn't be any whitespace because a user would make sure they didn't have a 6 column with nothing else after that in that row. 

But anyway, what if the `columns` addition just made a row with one large column (the HA equivalent of `col s12` in MaterializeCSS) and it was up to the end user to add `horizontal-stack` to add as many or as few columns as they needed?

```yaml
- type: columns
  cards:
    - type: horizontal-stack
      cards: # Would stretch two cards along the whole width of the page
        - type: picture-entity
          image: /local/bed_1.png
          entity: light.ceiling_lights
        - type: picture-entity
          image: /local/bed_2.png
          entity: light.bed_light
```

Keep in mind that I'm basing this off my experience with frameworks such as Bootstrap and MaterializeCSS, and that I haven't actually dived into HA's frontend stuff to see if it's using a similar grid system or doing it in a way that would make this idea incompatible.
