### ISSUE TITLE
[Feature request] Explicit entity attribute

### ISSUE THREAD

**Issue by cgtobi** [home-assistant/ui-schema#126]
Be able to explicitly define an attribute to be shown in the front end.

Use case: Climate devices usually have at least a current and a set temperature, but right now neither are shown by default. It would be pretty neat to be able to explicitly set an attribute to be shown in the UI.

e.g.:
```yaml
- entity: climate.livingroom
  name: Livingroom
  attribute: current_temperature
```
