### ISSUE TITLE
Multi-sensor card

### ISSUE THREAD

**Issue by c727** [home-assistant/ui-schema#13]
What do you think about this card? It will render like an `entities` card but show only 1 sensor/entity and its attributes

the stateObj looks like this
```yaml
sensor.livingroom:
  state: xxx
  attributes:
    temperature: 25
    humidity: 70
    battery: 80
    whatever: blub
```

This will render "all" (filter things like u_o_m or friendly_name). Attributes get a default icon. Special handyling for attributes like battery -> icon, u_o_m 
the card is configured like this
```yaml
- type: multi-sensor
  entity: sensor.livingroom
```

optional configs for the attributes
```yaml
- type: multi-sensor
  entity: sensor.livingroom
  attributes:
    temperature:
       icon: mdi:alert
       unit_of_m.: °C
       hidden: true
       friendly_name: Temp
```

Maybe later this can have a 2nd config option to render something like the plant card: https://user-images.githubusercontent.com/16738570/40282855-0081b8b2-5c6d-11e8-9b94-3f324a350ac6.png
