### ISSUE TITLE
Filtering is not working for all card types

### ISSUE THREAD

**Issue by moskovskiy82** [home-assistant/ui-schema#134]
Will reference #125 

The demo shows that filtering is possible. It works with a media player card but not with other types.
For example below config when state is satisfied:

      - type: entity-filter
        entities:
          - light.zwave_zal_small_level
        state_filter:
          - 'on'
        card:
          type: entities
          entities:
            - media_player.kodi_cinema
            - input_number.zal_onkyo_volume
            - input_select.onkyo_mode

Renders only:
![image](https://user-images.githubusercontent.com/15857592/43178486-6a05af4a-8fd6-11e8-94c0-97127ed9932a.png)

Same if we change for glance type card:

![image](https://user-images.githubusercontent.com/15857592/43178538-a8042aec-8fd6-11e8-8c01-b68ad0f84fc9.png)

**Comment by balloob** [comment]
Oh, I guess that is where the hack stops working 🤔 

The filter card will override the entities prop. If you are rendering a single entity card, like media player, the entities option is just ignored. With an entities card not so much.

**Comment by moskovskiy82** [comment]
Any chances of another behavior being implemented? This will be an extremely useful feature de cluttering the frontend

**Comment by c727** [comment]
It was a failure to abuse entity filter for this.

This is maybe an option, not sure if we want it in core
```yaml
- type: conditional-card
  conditions:
    - entity: light.test
      state: "on"
    - entity: switch.test
      state_not: "off"
  card:
    type: glance
```
