### ISSUE TITLE
history-graph caches the image between views

### ISSUE THREAD

**Issue by reevery** [home-assistant/ui-schema#135]
Hi

I have a couple of views which use history-graph but have different entities. When I switch between views, the graph needs a page refresh to get the correct graph.

Home:
![image](https://user-images.githubusercontent.com/4381067/43195638-94411372-8ffd-11e8-96fc-0422280b751f.png)
```
  - title: Home
    icon: mdi:home-assistant
    id: home
    cards:
      - type: history-graph
        title: Outside Temperature
        entities:
          - entity: sensor.yr_temperature
            name: YR
          - entity: sensor.owm_temperature
            name: OWM
          - entity: sensor.dark_sky_temperature
            name: Dark Sky
```

Now off to Living Room:
![image](https://user-images.githubusercontent.com/4381067/43195680-ab9a5858-8ffd-11e8-8dae-da00e5845246.png)
```
  - title: Living Room
    id: lr
    cards:
      - type: history-graph
        title: Temperature
        entities:
          - entity: climate.living_room
            name: ac
          - entity: sensor.kitchen_temperature
            name: Kitchen
          - entity: sensor.dark_sky_temperature
            name: outside
```

Then F5 (refresh), to what Living Room should be like:
![image](https://user-images.githubusercontent.com/4381067/43195622-88baff5e-8ffd-11e8-919c-f8981c8a5e8a.png)
