### ISSUE TITLE
history-graph selective attributes from climate entity

### ISSUE THREAD

**Issue by reevery** [home-assistant/ui-schema#136]
I have a history-graph card with a climate (ac) unit included. As you'll see from the screenshot below, I get all three graph items from climate: The setpoint, the temp, and the 'cooling' state. 

There are a few improvements I'd want to make, maybe these should be separate issues:
1. I'd like to remove the setpoint completely.
2. I'd like to remove the legend (I know what the values are).
3. Or, I'd like to remove the legend for the setpoint (although would prefer 2).
4. If I'm keeping the legend, I'd like to rename the sub-entities independently.
```
      - type: history-graph
        title: Temperature
        entities:
          - entity: climate.living_room
            name: ac
          - entity: sensor.kitchen_temperature
            name: Kitchen
          - entity: sensor.dark_sky_temperature
            name: outside
```
![image](https://user-images.githubusercontent.com/4381067/43195981-7a35e72c-8ffe-11e8-9410-9f386bec6307.png)
