### ISSUE TITLE
service-button ignores service_data

### ISSUE THREAD

**Issue by pschmitt** [home-assistant/ui-schema#142]
On HA 0.74.2, the `service_data` attribute seems to be ignored. No service data is passed in the wss call.

Config example:
```
- type: service-button                                                                                                                                                                 
  title: "Turn off lights"                                                                                                                                                                     
  service: homeassistant.turn_off                                                                                                                                                          
  service_data:                                                                                                                                                                               
    entity_id: group.all_lights
```
![screenshot](https://user-images.githubusercontent.com/37886/43450097-40217df4-94b2-11e8-8467-8a709a51af05.png)

See also the [reddit thread regarding this issue](https://www.reddit.com/r/homeassistant/comments/933plt/lovelace_picture_elements_card_service_data/).
