### ISSUE TITLE
History graph plotting incorrect element

### ISSUE THREAD

**Issue by shortbloke** [home-assistant/ui-schema#149]
Following on from issues #135 I've updated to 0.75.1 and things have improved but it's still not right.
Ahead of the fix for 135 I had a real mess of graphs not working, now it seems more limited. I have the following in one of my views:
```
      - type: history-graph
        title: Temperature
        entities:
          - entity: sensor.aeotec_zw100_multisensor_6_temperature
            name: 'Temperature'
      - type: history-graph
        title: Humidity
        entities:
          - entity: sensor.aeotec_zw100_multisensor_6_relative_humidity
            name: 'Humidity'
```
When it's rendered by lovelace I end up with two graphs, both of which are showing humidity, not one for humidity and one for temperature.
![image](https://user-images.githubusercontent.com/13274408/43688389-78ad4230-98df-11e8-8c62-c1afcb902781.png)
