### ISSUE TITLE
State-icon in picture glance card does not change color

### ISSUE THREAD

**Issue by jer78** [home-assistant/ui-schema#153]
Not sure if this is a bug or if I’m just doing something wrong but for the life of me I cant get the icon to change colors based on whether my switch or input_boolean is on or off. Without the change of color, it’s just an icon? I’m assuming this must be a bug

**Comment by arsaboo** [comment]
I don't think that is a bug (may be the feature is not implemented yet). Currently, I am using `customize` to change the icon colors. See [here](https://github.com/arsaboo/homeassistant-config/blob/master/customize_glob.yaml).

**Comment by jer78** [comment]
Thanks @arsaboo. I am using your suggestion of customize but I think that may be a workaround since the themes should determine the on/off color?? It would be nice to have the colors in the themes and Lovelace use those unless it’s specifically called out in the style section.

**Comment by nessinot** [comment]
I noticed the same thing. I added a group which consists of two lights to the glance card. I changed the icon to mdi:lightbulb. When off it looks just like the other lights in de glance card. However, when the group is on, the icon stays the same color. 

Would be nice if this would change like the rest, or to have an option to configure the icon color based on state. 

`- type: glance
  title: Living room
  entities:
    - entity: group.couch_lights
      name: Couch
      tap_action: toggle
      icon: mdi:lightbulb
    - light.table`

**Comment by iantrich** [comment]
@nessinot try a light group instead

**Comment by nessinot** [comment]
Wow, never knew that existed. It solved my problem. 

Thanks @iantrich

**Comment by DavidFW1960** [comment]
> I don't think that is a bug (may be the feature is not implemented yet). Currently, I am using `customize` to change the icon colors. See [here](https://github.com/arsaboo/homeassistant-config/blob/master/customize_glob.yaml).

I tried this with the input_boolean but it doesn't work.

![image](https://user-images.githubusercontent.com/36390762/51153906-03ed8600-18c6-11e9-90ee-a183f178cb03.png)

It's seeing the customization but my picture_entity in lovelace doesn't change colour

![image](https://user-images.githubusercontent.com/36390762/51153945-2e3f4380-18c6-11e9-9c84-53efb34b7085.png)

Or am I supposed to be using custom_ui or am I missing something?

```
  - cards:
      - type: 'custom:compact-custom-header'
      - cards:
          - entities:
              - input_boolean.alarmgaragedoor
              - switch.sonoff51083
              - switch.sonoff63719
            show_header_toggle: false
            title: Security
            type: entities
          - cards:
              - entity: switch.sonoff51083
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data:
                    entity_id: switch.sonoff51083
                type: entity-button
              - entity: switch.sonoff63719
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data:
                    entity_id: switch.sonoff63719
                type: entity-button
              - entity: input_boolean.alarmgaragedoor
                name: Exit-Enter
                tap_action:
                  action: call-service
                  service: input_boolean.toggle
                  service_data:
                    entity_id: input_boolean.alarmgaragedoor
                type: entity-button
```

**Comment by thomasloven** [comment]
Templates in `customize` is from custom-ui. It's not a feature of Home Assistant.

**Comment by matisaul** [comment]
I think this would be a nice new feature... I use a lot of input boolean as a switch, but I can't use the entity-button card for this.

**Comment by fryguy04** [comment]
+1 for this ... Seems like a very common need ... to show Button icons that reflect the state (ideally entity-button?). Anyone have a work around until this is implemented?

**Comment by VDRainer** [comment]
+1
Changed all my custom:button-cards (I'm tired of it) to entity-button and having the same problem.
State for input_booleans and automations not colored.
A workaround is using the state-switch from thomasloven with two cards for one entity.

**Comment by balloob** [comment]
Each time this comes up, I say the same thing: don't suggest that we need to color this or that, instead, come up with a strategy that we can use for each place (entity row, entity button etc) on how we should color each type of entity/device class and each of their states.

**Comment by arsaboo** [comment]
@balloob How about something like `state_color`, which should work like our current `state_icon`?

**Comment by VDRainer** [comment]
Hmm...
If an entity is 'on' -> color (like the switch and the light already does)

**Comment by balloob** [comment]
Adding a config option so you have a tool solve your problem won't solve it for others, but instead requires each user to solve the same problems.

**Comment by arsaboo** [comment]
Not sure I understand your comment Paulus. Are you opposed to having a config option to change colors?

**Comment by balloob** [comment]
I would prefer that we have a icon coloring strategy for each entity component

**Comment by arsaboo** [comment]
We can have a default coloring strategy (like yellow if `on`), but a) it will be quite limiting, and b) not sure if it will work with themes.

**Comment by RezzZ** [comment]
+1 for adding support for color changes for all entities that can have a status on/off. This is already working for lights, switches and binary_sensors (like door/motion sensors) but not for input_booleans which also have a status on or off.
Only workaround right now is to create an extra template sensor on top of the input boolean so that we can give it a proper device_class which helps setting icon and color in lovelace. This could/should be easier to do though.

**Comment by iantrich** [comment]
So get the ball rolling on this I plan to implement `icon_color` for all cards that have icons; at the entity level if it supports multiple entities per card.

From there, I would like to develop some sort of `state-config-merge` card where you could define a state filter to match against that would then provide config changes to the underlying card

e.g.

```yaml
type: state-config-merge
states:
  - value: on
    config:
      icon: mdi:bulb
card:
  type: light
  entity: light.bed
  icon: mdi:lamp
```
