### ISSUE TITLE
picture-elements card size

### ISSUE THREAD

**Issue by hekm77** [home-assistant/ui-schema#156]
Image size 720x1000px

On my desktop i see:
<img width="1182" alt="111" src="https://user-images.githubusercontent.com/22895433/44299935-f45e1700-a2fe-11e8-94e1-70901089f61c.png">
On iPhone 5S i see cropped card.
I can not scroll down.
<img width="300" alt="222" src="https://user-images.githubusercontent.com/22895433/44299938-06d85080-a2ff-11e8-9e94-bced1c7fd8ec.png">
```
    cards:
      - type: picture-elements
        image: /local/bg/bg.png
        elements:
          # tile_1
          - type: state-label
            entity: sensor
            style:
              top: 168px
              left: 0%
              transform: none
              box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)
              background: rgb(44, 90, 140)
              width: 720px
              height: 135px
              opacity: 0.5
          # tile_2
          - type: state-label
            entity: sensor
            style:
              top: 330px
              left: 0%
              transform: none
              box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)
              background: rgb(44, 90, 140)
              width: 720px
              height: 135px
              opacity: 0.5
          # tile_3
          - type: state-label
            entity: sensor
            style:
              top: 492px
              left: 0%
              transform: none
              box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)
              background: rgb(44, 90, 140)
              width: 720px
              height: 135px
              opacity: 0.5
```
