### ISSUE TITLE
Proposal: Button entity row

### ISSUE THREAD

**Issue by paulbdavis** [home-assistant/ui-schema#172]
### Use cases

- combine singe action entities into a more compact row
- add buttons to trigger events
- add buttons to simplify things with many choices (media_player source, light effects)

### Examples

![card1](https://user-images.githubusercontent.com/2730634/46573871-1c114900-c958-11e8-8c5c-eb83c77997bb.jpg)

```yaml
      - type: entities
        title: Living Room Lights
        show_header_toggle: false
        entities:
          - type: button
            buttons:
              - icon: mdi:lightbulb-on
                icon_color: yellow
                name: "On"
                service: events.ut_lights_up
              - icon: mdi:lightbulb
                icon_color: grey
                name: "Off"
                entity: scene.lights_out
              - icon: mdi:movie
                icon_color: red
                name: Movie
                entity: scene.movie_lights
```

![card2](https://user-images.githubusercontent.com/2730634/46573872-203d6680-c958-11e8-8949-8d258c7048e1.jpg)

```yaml
          - type: button
            buttons:
              - name: "Power"
                icon: mdi:power
                icon_color: yellow
                entity: switch.tv_power
              - name: "Home"
                service: media_player.select_source
                service_data:
                  source: Home
          - type: button
            buttons:
              - icon: mdi:volume-minus
                entity: switch.tv_volume_down
              - icon: mdi:play-pause
                entity: media_player.roku
              - icon: mdi:volume-plus
                entity: switch.tv_volume_up
          - type: button
            buttons:
              - name: "Netflix"
                service: media_player.select_source
                service_data:
                  entity_id: media_player.roku
                  source: Netflix
              - name: "Hulu"
                service: media_player.select_source
                service_data:
                  entity_id: media_player.roku
                  source: Hulu
          - type: button
            buttons:
              - name: "HBO"
                service: media_player.select_source
                service_data:
                  entity_id: media_player.roku
                  source: HBO GO
              - name: "Prime"
                service: media_player.select_source
                service_data:
                  entity_id: media_player.roku
                  source: Amazon Prime Video
```

[Implementation](https://github.com/home-assistant/home-assistant-polymer/pull/1741)
