### ISSUE TITLE
entities card does not present header toggle for automation entities

### ISSUE THREAD

**Issue by steve28** [home-assistant/ui-schema#176]
I have an entities card with all of my automations on it for ease of disabling when guest are over, I am working on something, etc.  In doing so, I have noticed that on an `entities` card that only contains `automation` entities, there is no header toggle presented.  For example:

```yaml
- type: entities
  title: Test Card
  entities:
    - automation.apartment_alarms
    - automation.arrive_actions
    - automation.attic_lights_autooff
```
shows:
![image](https://user-images.githubusercontent.com/5874433/46918435-197da780-cf87-11e8-97c1-5ff9a78534ce.png)
Also, `show_header_toggle: true` has no effect.

I would expect there to be a group toggle at the top to allow turning off all the automations at once.
