### ISSUE TITLE
history-graph plots wrong info

### ISSUE THREAD

**Issue by steve28** [home-assistant/ui-schema#193]
Seems related to: #149 - but it's still not working correctly as of 0.82.1

I made a vertical-stack showing two history-graphs of the same sensor.  One to show the default "past 24 hours" and one to show only the last hour.  Like so:
```yaml
      - type: vertical-stack
        cards:
        - type: history-graph
          title: House Power - 24 Hours
          entities:
            - sensor.house_power
        - type: history-graph
          title: House Power - 1 Hour
          hours_to_show: 1
          entities:
            - sensor.house_power
```
When I do this, I get the exact same graph twice:
![screen shot 2018-11-16 at 12 35 55 pm](https://user-images.githubusercontent.com/5874433/48646826-d3a96a00-e99e-11e8-91cd-938207c0274c.png)
Some more info:
- If I refresh the page a bunch of times, it will occasionally load correctly.
- If I add a `refresh_interval:` to the 1-hour graph, it will oscillate back and forth between the correct plot and the incorrect plot.  Specifically, the correct one will load and few seconds later, it will flip back to the incorrect one, this seems to repeat every `refresh_interval`.
- If I switch the order (i.e., put the 1-hour graph first), it seems to work correctly
