### ISSUE TITLE
Check if stateObj exists before trying to render cards

### ISSUE THREAD

**Issue by Bodge-IT** [home-assistant/ui-schema#20]
I had 7 switches configured, 3 of which stopped working after a re-org of docker hosts.  I still added all 7 entities to my 2nd card of 5 in a view, with the broken 3 first.  I got the title of card 2 but no entities and no other cards.

After commenting the broken 3 all other entities and cards appeared as expected.

Expected behaviour:
Just don't show missing/failed entities but continue to show follwing entities and cards

Hass v 0.72b9
Running in Docker container (not hass.io)

**Comment by balloob** [comment]
Error in logs?

**Comment by Bodge-IT** [comment]
```
name: Winchy
views:
    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
  - name: LoftWorks
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: light-mode
    # The cards to show on this view.
    cards:
        # The entities card will take a list of entities and show their state.
      - type: entities
        title: 'Containers on Peapod'
        entities:
          - switch.plex
          - switch.plexpy
          - switch.lms
          - switch.musicip
          - switch.sabnzbd

      - type: entities
        title: 'Containers on Kube'
        entities:
          - switch.mqtt
          - switch.organizr
          - switch.nodered
          - switch.sonarr
          - switch.radarr
          - switch.lidarr
          - switch.headphones

      - type: entities
        title: 'Containers on Zepher'
        entities:
          - switch.hass
          - switch.unifi

      - type: entities
        title: 'SABnzbd Status'
        entities:
          - sensor.sabnzbd_status
          - sensor.sabnzbd_disk
          - sensor.sabnzbd_disk_free
          - sensor.sabnzbd_left
          - sensor.sabnzbd_monthly_total
          - sensor.sabnzbd_queue_count
```
