### ISSUE TITLE
Thermostat Card Clipping

### ISSUE THREAD

**Issue by kflinderman** [home-assistant/ui-schema#221]
Hello,

I just wanted to point out that the thermostat card does not play well in a horizontal stack with any small browser window (really mobile is where I see it the most).  Just feel like at least it should not clip out the bottom buttons but should still be able to be stacked horizontally.  Doesn't make sense for this to be one of the exceptions.

https://imgur.com/a/nPr24VH

**Comment by ZenDIY** [comment]
Hello,
I am facing the same issue reported by @kflinderman. The thermostat card is OK when the smartphone is in vertical position, but when I rotate my smartphone the card seems to be clipped and bottom icons/commands disappears.

![mobile_horizontal](https://user-images.githubusercontent.com/25845078/51029324-4ba6a180-1596-11e9-8892-a2802427b6c0.png)
![mobile_vertical](https://user-images.githubusercontent.com/25845078/51029325-4ba6a180-1596-11e9-8292-be61feb7482d.png)

**Comment by iantrich** [comment]
This is fixed now, I believe

**Comment by kflinderman** [comment]
It is much better than it used to be.  I still get a slight clipping on the bottom for a normal window.  But I can also really screw with it if the window gets tiny.  Not sure if that should be looked at or not, cause I really had to make it small to get there.  Here are the two pictures I took, the first one is what I see on mobile, the second is what I got to look wonky.

https://imgur.com/cZ15iPr
https://imgur.com/DY9BReL

**Comment by Misiu** [comment]
Unfortunately, there are still issues with the thermostat card.

 ![image](https://user-images.githubusercontent.com/1741838/63983509-50897880-cac7-11e9-9423-7c515c60ab1f.png)

The config I have is really simple:

```
type: vertical-stack
cards:
  - cards:
      - entity: climate.study
        type: thermostat
        name: Kuchnia
      - entity: climate.study
        type: thermostat
        name: Sypialnia
    type: horizontal-stack
  - cards:
      - entity: climate.study
        type: thermostat
        name: Pokój dzienny
      - entity: climate.study
        type: thermostat
        name: Korytarz
    type: horizontal-stack
```

When You have 2x2 grid with thermostats it looks quite good on PC (Win10 Chrome 76), but on mobile, it looks terrible:
![image](https://user-images.githubusercontent.com/1741838/63983919-305ab900-cac9-11e9-8f2e-70b856af1f50.png)

is there a chance to fix the cropping issue? Also, can the thermostat card adjust font size based on its size?
I manually changed the font size in cards and it looks much better (two bottom left cards):
![image](https://user-images.githubusercontent.com/1741838/63984209-6a788a80-caca-11e9-9884-c7d567d497cb.png)

@iantrich  Can the font size be dynamic? Based on card size?
