### ISSUE TITLE
State history chart changes to wrong entity graph after some seconds

### ISSUE THREAD

**Issue by braegel** [home-assistant/ui-schema#231]
After clicking on an entity badge I get this correct "state history graph":

![image](https://user-images.githubusercontent.com/112244/51806337-32317500-2279-11e9-9f68-664de8eaa864.png)

After some seconds (or maybe after some mouse movements) the graph changes to a wrong entity:

![image](https://user-images.githubusercontent.com/112244/51806347-45dcdb80-2279-11e9-86a2-6b4bdab4f785.png)

Relevant extract from my configuration.yaml:
```yaml
- platform: template
    sensors:
      eddw_crosswind_270:                                                                               
        friendly_name: "Crosswind EDDW 270"                                                             
        unit_of_measurement: 'kt'                                                                       
        value_template: " {{ sin( (states('sensor.dark_sky_wind_bearing')|float - 270) * pi / 180) * states('sensor.dark_sky_wind_speed')|float * 1.9438 }}"                                                   

- platform: mqtt
  state_topic: phoh/temperature
  name: "Familienraum temperature (BME280)"                                                           
  unit_of_measurement: '°C'                                                                           
  device_class: temperature                                                                           
```
Home Assistant 0.86.3
