### ISSUE TITLE
Why is text on entity-button always uppercase? 

### ISSUE THREAD

**Issue by zombiehunter1** [home-assistant/ui-schema#232]
Been adding some entity buttons for some reason the button name is always in uppercase 
can I override this, It should display exactly what is in the name attribute 
```
- entity: switch.downstairs_lights
        icon: 'mdi:page-layout-footer'
        name: 'Downstairs Lights' 
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.downstairs_lights
        type: entity-button
```
