### ISSUE TITLE
FR: glance (show_icon)

### ISSUE THREAD

**Issue by jakeapp** [home-assistant/ui-schema#234]
If you've got a glance card and want to hide the icon and show just the name and state i.e. for a series of same sensors that could tighten up the front-end nicely.
```
card:
  type: glance
  # could also maybe add persistent flag for 'show_icon:' flag here
  columns: 2
    entities:
      - entity: sensor.room_temp
        show_icon: false
      - entity: sensor.room2_temp
        show_icon: false
```

Having the flag default to true would allow users to keep configurations as is...

(previously this FR referenced an option to hide or show the name of a entity-button card.  Turns out it is possible to hide the name of an entity button in a hacky kind of way with the following yaml code:

```
type: entity-button
entity: switch.stereo
name: ' '
icon: mdi:power
```
so this works and all is good)
