### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#25]
Right now we have adopted the column algorithm from the states panel. It works ok to make sure the whole screen is evenly filled up. However, people might want more control:

 - Allow to set a fixed column count - how do we choose which entities go in which column?
 - Change the screen width breakpoints when we add another column
 - Have a `column-card` that can define multiple columns?

```yaml
- type: columns
  columns:
  # First column
  - - type: entities
      entities: []
    - type: glance
      entities: []
  # Second column
  - - type: entities
      entities: []
    - type: glance
      entities: []
```

(not a fan of this syntax!)

**Comment by balloob** [comment]
Maybe we should just add a split-card that can render two cards ? 

```yaml
- type: split
  left:
    type: entity-picture
    entity: switch.kitchen
  right:
    type: entity-picture
    entity: switch.ac
```
