### ISSUE TITLE
Add split card

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#27]
Add a card that allows to render other cards that are splitting the width available to the split card

(config courtesy of @arsaboo in https://github.com/home-assistant/ui-schema/issues/25#issuecomment-399455697)

```yaml
- type: split
  cards:
    - type: entity-picture
      entity: switch.kitchen
    - type: entity-picture
      entity: switch.ac
    - type: entity-picture
      entity: switch.livingroom
```
