### ISSUE TITLE
Dynamic way of picking entities for a card

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#3]
Problem: I want to create a card that will select the entities to show based on a user specified filter. For example, show a card with all lights that are on.

Proposed Solution: encapsulation. Have a card that takes an expression and produces a list of entities that it will forward to an embedded card.

By default the filter will show the entities in an entity card, but this could be overridden.

```yaml
# Example card config
type: entity-filter
filter:
  domain: light
  state: on
card: entities-graph . # defaults to 'entities'
card_config:
  card-specific: config
```
