### ISSUE TITLE
entity-filter returns all entities instead of the filtered ones

### ISSUE THREAD

**Issue by schmic** [home-assistant/ui-schema#31]
Using that configuration returns a card with all entities, except for the filtered ones.

```
- type: entity-filter
        filter:
          - entitiy_id: "automation.temperatur_*"
        card_config:
          title: "Temperaturregelung"
```
