### ISSUE TITLE
entity-filter hidden items

### ISSUE THREAD

**Issue by erikmohn** [home-assistant/ui-schema#32]
New entity-filter card shows items that should be hidden from the UI.

Entity filter: 
```
      - type: entity-filter
        filter:
          - domain: light
            state: 'on'
          - domain: switch
            state: 'on'
        card_config:
          title: Belysning i bruk
```

Hidden items that show up in the UI
```
light.spisebord1:
  hidden: true
light.spisebord2:
  hidden: true
```
