### ISSUE TITLE
Entities-card: Horizontal lines between entities

### ISSUE THREAD

**Issue by covrig** [home-assistant/ui-schema#43]
@c727  I have [simple git](https://github.com/covrig/homeassistant-hline) that @arsaboo suggested me move to Lovelace. Basically it adds a horizontal line between some entities helping a bit with the grouping/highlighting.

I was thinking to link it to the entities card for the start (but can be added to other card in the future). Do you see this as a good idea? It should be relatively easy to implement. I was thinking to use an `if` in the `for `loop modifying the css - e.g. border top of the next sensor if the - horizontal-line is present.
There are many ways to accomplish this. Maybe we could allows some options: color, type, thickness etc.
```
  - type: entities
    title: Entities card sample
    entities:
      - input_boolean.switch_ac_kitchen
      - input_boolean.switch_ac_livingroom
      - input_boolean.switch_tv
      - horizontal-line
      - sensor.yweather_pressure
      - sensor.yweather_temperature
```
![capture](https://user-images.githubusercontent.com/8059190/41876774-3a47bd70-78cf-11e8-90f1-5db0c9ca8008.JPG)

**Comment by balloob** [comment]
We should treat each entry for entities as a more complicated object with a shortcut version.

```yaml
- type: entities
  entities:
   - input_boolean.switch_ac_kitchen
```

is a shortcut for:

```yaml
- type: entities
  entities:
   - type: default
     entity: input_boolean.switch_ac_kitchen
```

![blog-divider8](https://user-images.githubusercontent.com/1444314/41877773-727052d6-78a0-11e8-8a7b-e6d5c8ce5ee4.png)
Now that we have more advanced configs, we can do a similar approach as we did for cards:

 - allow new types, like `divider-picture`, `divider-line`, etc.
 - allow custom render types for individual entities (`custom:my-toggle-display`)

```yaml
- type: entities
  entities:
   - type: default
     entity: input_boolean.switch_ac_kitchen
   - type: divider-picture
     image: https://example.com/bla
   - type: divider-line
     color: red
     thickness: 5px
     type: dashed
```
