### ISSUE TITLE
Add picture card and place entities based on coordinates

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/ui-schema#52]
Picture-glance: Enhancement - support coordinates for positioning elements inside the card
Or maybe a new type of card that allows coordinates to position entities on the card.

Use case: More flexibility on big tile dashboards.

**Comment by c727** [comment]
I also thought about this
- image width should be 600px
- positioning should care of current scale factor

**Comment by balloob** [comment]
Let's make this a new card.

Positioning should be in percentages so width can vary. We can use `position: absolute` and use CSS `top: 10%` and `left: 10%`.

Would we just want to render the icon on the picture if it's a toggle entity and icon + state if it's a sensor ? (probably using badge without the name?)

Can't tap sensor, tapping the other entities toggles them.

**Comment by c727** [comment]
current progress. have to find some restrictions in the endless possible settings :thinking: 
```yaml
      - type: entities-gone-wild
        title: entities-gone-wild
        image: /local/floorplan.png
        entities:
          - type: text
            text: My house
            top: 5%
            left: 50%
            style: "color: white; background-color: red; padding: 0 8px;"
          - type: state
            entity_id: sensor.temperature
            top: 50%
            left: 55%
          - type: badge
            entity_id: light.ceiling_lights
            top: 30%
            left: 55%          
          - type: button
            text: light
            icon: mdi:power
            domain: light
            service: turn_off
            service_data:
              entity_id: light.ceiling_lights
            top: 20%
            left: 82%
```
![unbenannt](https://user-images.githubusercontent.com/11984118/41932635-c68ac8ba-7981-11e8-810f-ca2a648e15d6.PNG)
