### ISSUE TITLE
Horizontal Stack Bug with Camera's

### ISSUE THREAD

**Issue by jackjohnsonuk** [home-assistant/ui-schema#65]
It appears when putting Camera's in horizontal stack's you lose the ability to click and get an expanded view of the camera.

yaml being used as below:

```yaml
    - type: horizontal-stack
      cards:
        - type: camera-preview
          entity: camera.front_door
        - type: camera-preview
          entity: camera.kitchen
        - type: camera-preview
          entity: camera.living_room
```
