### ISSUE TITLE
history-graph produces "Entity not defined in card config" red card

### ISSUE THREAD

**Issue by sagilo** [home-assistant/ui-schema#84]
I've tried creating history-graph card on version 0.72.1 and later updated to 0.73.0
Both version produces red error like card with "Entity not defined in card config".

![Error](https://image.ibb.co/fKGn7T/Screenshot_from_2018_07_08_12_04_04.png)

```
      - type: history-graph
        title: Temperatures
        hours_to_show: 48
        entities:
          - sensor.darksky_weather_temperature
          - sensor.temperature_158d0001b920fc
          - sensor.temperature_158d0001b95f87
```
I've double checked all the sensors id's are valid.
