### ISSUE TITLE
horizontal-stack

### ISSUE THREAD

**Issue by justinw78** [home-assistant/ui-schema#85]
Hello, 

With the card horizontal-stack i got the next problem (see picture)
The width isnt the same from the cards. 
![example](https://user-images.githubusercontent.com/8213938/42419918-ea11aea8-82bd-11e8-8fc5-f7e9ef6f827e.png)

my configuration is 
```yaml
- icon: mdi:delete-empty
    title: Afvalkalender
    cards:
     - type: horizontal-stack
       cards:
         - type: 'custom:content-card-example'
           entity: sensor.afval
         - type: 'custom:content-card-tijd'
           entity: zone.home
```
I hope someone can help with it

Greetings justin
