### ISSUE TITLE
Feature Request: Dynamically Show/Hide a View

### ISSUE THREAD

**Issue by rtclauss** [home-assistant/ui-schema#94]
In the current UI I have a set of [automations](https://github.com/rtclauss/hass-config/blob/master/packages/trips.yaml#L292-L306) and a [script](https://github.com/rtclauss/hass-config/blob/92066a0d130d4b1bb7398f201905abb98dc30219/script.yaml#L7-L13) that toggles a view's visibility based upon a matching condition such as being on a trip or Christmastime.

It'd be nice to toggle the visibility of a tab based upon some condition or by calling some built-in service.

**Comment by balloob** [comment]
Use the entity-filter

```
      - type: entity-filter
        entities:
          - media_player.rasplex
        state_filter:
          - 'playing'
        card: 
          type: media-control
          entity: media_player.rasplex
```

(it's currently not 100% working due to a bug with a couple of cards but that will be fixed in 0.74)
