### ISSUE TITLE
Panel view and  custom cards  aren't compatible

### ISSUE THREAD

**Issue by nlinnett** [home-assistant/ui-schema#95]
If I setup a view to be a panel, and the first card is of type "custom:monster-card" then I get the red error box saying "Custom element doesn't exist: monster-card". (I've also found the same issue with custom:weather-card"

If I remove the panel: true line from the view definition, it works properly.
```
  - title: What's On
    panel: true
    icon: mdi:alarm-bell
    id: whats_on
    cards:
      - type: "custom:weather-card"
        entity_weather: weather.yweather
        entity_sun: sun.sun

      - type: glance
        title: devices
        entities:
          - device_tracker.b072bf3f0f0b
          - device_tracker.etarapyr_dreamqltecan

      - type: "custom:monster-card"
        card:
          type: glance
        filter:
          include:
            - domain: device_tracker
```

Also, there seems to be no way to have additional cards show up. Is this only a temporary restriction?
