### ISSUE TITLE
Feature Request: Last changed for entities in entities card

### ISSUE THREAD

**Issue by pleeja** [home-assistant/ui-schema#97]
Once it was possible to show last changed text in Home Assistant but they removed the feature I believe. 
Maybe Lovelace can bring it back?

What I want: (now achieved with custom-UI by Andrey)

<img width="501" alt="schermafbeelding 2018-07-11 om 09 00 26" src="https://user-images.githubusercontent.com/41104650/42555709-7dad5c98-84e9-11e8-9183-df3e8666db46.png">

Example config:

```
cards:
   - type: entities
     title: Kitchen
     entities:
       - entity: light.kitchen_ceiling_light
         show_last_changed: true
```

**Comment by balloob** [comment]
Yes, now that we have easy options for rows, I agree that we can bring this back as an option.

However, I think that I would want to implement the option slightly differently, to allow more flexibility:

```
cards:
   - type: entities
     title: Kitchen
     entities:
       - entity: light.kitchen_ceiling_light
         second_line: last_changed
```

For now it would just support last changed, but allows more flexibility for the future. btw probably need a better name than `second_line` but lacked creativity.
